### ISSUE TITLE
RAWNAND  "Not a valid Nx Storage"

### ISSUE THREAD

**Issue by medber** [eliboa/NxNandManager#10]
After making a FULL DUMP of 8.1 to ->RAWNAND.bin and a somehow failed 9.01 update I´m not able to write this backup back with FULL RESTORE and get the error  "Not a valid Nx Storage". 

![error3](https://user-images.githubusercontent.com/6376844/68077478-0e313000-fdc5-11e9-9258-6ca4f279d420.PNG)

**Comment by eliboa** [comment]
Can you open RAWNAND.bin from NxNandManager (CTRL+O) ?

**Comment by eliboa** [comment]
Ok, I can see where the problem is. Backup GPT is not found for drive mounted through memloader.
I'll look into it. Thank you.

**Comment by eliboa** [comment]
Let me know anyway if you can open RAWNAND file with CRTL+O

**Comment by medber** [comment]
> 
> 
> Let me know anyway if you can open RAWNAND file with CRTL+O

Nope. Seems not to work...

**Comment by eliboa** [comment]
Fixed b7d2def. https://github.com/eliboa/NxNandManager/releases/tag/v3.0.2

Unfortunately, you'll have to make a NAND backup again or find a way to add GPT backup manually. If you can find a way to copy GPT header at sector 2 of RAWNAND.bin (512 bytes at offset 512), then you just have to paste those bytes at the end of file.
