### ISSUE TITLE
Program not detecting emuMMC partition(s) on plugged in SD card

### ISSUE THREAD

**Issue by FusionFernia0000** [eliboa/NxNandManager#12]
The SD Card is a Samsung MicroSDXC EVO Plus 256GB
Divided into 3 partitions: 1) FAT32 storage 2) an 8GB emuMMC partition 3) a 30GB emuMMC partition

Tried with the following configurations, the Physical Drives window showed blank (using v3.0.3 and v3.0.1)

SD card plugging into a USB Type C dongle, then into PC
SD card plugging into a microSD to USB converter, then to the USB Type C dongle, then into PC
SD card plugging into a microSD to USB converter, then into PC

The emuMMC images are flashed onto the SD card with makeEmu.exe, if that matters.
Pressing the Question mark button just freezes the Physical Drive window.

![Capture](https://user-images.githubusercontent.com/20417687/69477264-0b9f8480-0e1f-11ea-8e19-5491c44d849e.PNG)

**Comment by eliboa** [comment]
Thank you for reporting this. I'm not surprised the program doesn't detect emuMMC on drive that contains more than 1 emuMMC because I never tested it ^^. I'm gonna look into this.

**Comment by FusionFernia0000** [comment]
On another note, all 3 partitions are primary partitions (the FAT32 partition's drive letter can be changed, but the other 2 partitions' drive letter can't be modified, probably a windows quirk) and not logical partitions, I've also tried a SD card with only one emuMMC partition but still with no luck.

I might be able to test with another PC and report back later.

**Comment by eliboa** [comment]
Yes, MBR for removable drive only allow one primary partition, and Windows can only attribute a drive letter for primary partition. 
What is your emuMMC offset in the ini file generated by hekate when using "Migrate emuMMC" tool ?

**Comment by FusionFernia0000** [comment]
0x19233800 for the 8GB partition and 0x1A267800  for the 30GB partition.

**Comment by eliboa** [comment]
And what are the first sector (on disk) for each of these partitions ?

**Comment by FusionFernia0000** [comment]
421,738,496‬ and 438,728,704‬ respectively.
It's basically just hexadecimal to decimal conversion.

**Comment by m0neyta1ks** [comment]
Hello there. I have exactly the same issue with a Samsung 512gb Evo Select U3 running only a single emuMMC partition. Tried to replicate the issue with my other Sandisk cards, but it seems to be exclusive the Samsung mentioned above.

**Comment by eliboa** [comment]
Could someone dump and send me the first sectors of his samsung EVO mmc (32 Mb should be ok) please ?
This can be done by using "dd for windows" for example.
Thank you

**Comment by FusionFernia0000** [comment]
Dumped with dd for windows with the command [C:\dd bs=4000k count=1 if=\\?\Device\Harddisk3\Partition0 of=C:\32Mb.img --progress]

Not sure if I did it correctly tho (or if it contain personal data even).

[samsung_first_32Mb.zip](https://github.com/eliboa/NxNandManager/files/4160099/samsung_first_32Mb.zip)

Also tried my SanDisk 64GB SD card a while back with only 1 emuMMC partition, couldn't detect anything, so I imagine this might not even be a specific brand issue.

**Comment by eliboa** [comment]
@FusionFernia0000 thank you, i'll look into it.
I do plan to add a feature to list all disks and volumes, not just the "compatible" ones.

**Comment by kieranearth** [comment]
![image](https://user-images.githubusercontent.com/57925463/74603220-38270d80-50a9-11ea-96ef-079db006dc7e.png)
 
I have the same issue when I try to open my drive with the Emunand partition it just shows a white box and wont mount my EMUnand partition. I have tried the using the switch to mount the sd card and also in my sd card reader. it only have one partition on the sdcard, I've attached a screenshot hopefully it helps.

**Comment by kieranearth** [comment]
> @FusionFernia0000 thank you, i'll look into it.
> I do plan to add a feature to list all disks and volumes, not just the "compatible" ones.

I've just commented as I'm having a similar issue but not sure it is deserving of its own issue? I've posted it in the comments here

**Comment by eliboa** [comment]
Hi folks, would you mind testing this [alpha version](https://drive.google.com/open?id=1HuqmJWiSTF0M4PkcTiALXCimBi9zUpBo) and telling me if you can open your emummc partition ?
You can now choose to open any disk or volume (CTRL+D or File> Open drive)

**Comment by FusionFernia0000** [comment]
Confirmed working. Just dumped my 8GB and 30GB emuMMC (raw dump) like slicing butter.
Tho haven't tested writing to the SD card yet, but I'll assume it works.

![image](https://user-images.githubusercontent.com/20417687/75097408-752d5b80-55e5-11ea-8ed9-d726c3923cd5.png)

**Comment by eliboa** [comment]
@FusionFernia0000 thank you.

**Comment by FusionFernia0000** [comment]
Thank you for the time and effort you spent on this project as well. This software will be very useful for me when I deal with backups and such. :)
