### ISSUE TITLE
Dump rawnand.bin in split files?

### ISSUE THREAD

**Issue by el-emmo** [eliboa/NxNandManager#13]
This would make it easier to, for example, dump the rawnand directly to a FAT32 SD card (which doesn’t work at the moment as the program will error out after the first 4GB are written).

**Comment by eliboa** [comment]
Hello el-momo. I plan to add this feature in next release. Stay tuned :)

**Comment by eliboa** [comment]
369023ba395b8fec809a82e4536c64f966bcd032

**Comment by eliboa** [comment]
In "Advanced dump" menu, check "Split output" checkbox and set chunksize field to 4000 Mb.
