### ISSUE TITLE
Does not load with wine on linux

### ISSUE THREAD

**Issue by blairfancy** [eliboa/NxNandManager#14]
Hi there is some regression in your tools. I m not able to run with wine in linux:

`wine NxNandManager.exe `
`terminate called after throwing an instance of 'std::runtime_error'`
`  what():  locale::facet::_S_create_c_locale name not valid`

`abnormal program termination`

Latest working version is 3.0.0

**Comment by eliboa** [comment]
Thank you for reporting this. This will be fixed in next release. Stay tuned.

**Comment by rlaPHOENiX** [comment]
This is still an issue

**Comment by eliboa** [comment]
Yes it is. As I said, this will be fixed in the next version.

**Comment by eliboa** [comment]
Hi, would you mind testing this [alpha version](https://drive.google.com/open?id=1HuqmJWiSTF0M4PkcTiALXCimBi9zUpBo) and telling me if it's working for you ?

**Comment by rlaPHOENiX** [comment]
Still fails, perhaps im missing a vc++ redist or .net framework? Also, you should try move from .NET Framework to .NET Core if you can as .NET Core is cross-platform and is getting very good recently.

**Comment by eliboa** [comment]
Is it still the same error ?
This project does not use .NET framework.

**Comment by speed47** [comment]
Jumping in on this.

the 4.0 alpha version still yields the same error message:

```
$ wine64 NxNandManager_v4.0a_x64/NxNandManager.exe
0009:fixme:actctx:parse_manifest_buffer failed to parse manifest (null)
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid

abnormal program termination
```

However, given the error message, I tried something and it works:

```
$ LANG=C wine64 /home/speed/Downloads/NxNandManager_v4.0a_x64/NxNandManager.exe --help
0009:fixme:actctx:parse_manifest_buffer failed to parse manifest (null)
[ NxNandManager v3.0.3 by eliboa ]

Argument (--help) is not allowed.

usage: NxNandManager -i <inputFilename|\\.\PhysicalDriveX>
           -o <outputFilename|\\.\PhysicalDrivekX> [Options] [Flags]

=> Arguments:

  -i                Path to input file/drive
  -o                Path to output file/drive
[...]
```

It works with both the alpha version and the latest stable version.

**Comment by qwertychouskie** [comment]
For me, I had to do `LC_ALL=C wine /path/to/NxNandManager.exe`
