### ISSUE TITLE
emuMMC Running slow with downsized USER Partition

### ISSUE THREAD

**Issue by Vampitech** [eliboa/NxNandManager#15]
Maybe isn't an error of NxNandManager but i left this issue here for the record. In many cases when i downsize the USER partition and flash the RESIZED image with DD (Windows Version) into the SD partition that i created for "mini" emuMMC, Hekate recognizes it but when i load HOS in that emuMMC the menu and games freezes. Can be any corruption or issue with the USER partition downsize process?? I tested this on 3 microSD (2 64gb SanDisk Ultra and 1 512gb Samsung EVO)

**Comment by eliboa** [comment]
Hi @Vampitech, how small is your mini-emunand ? Is it full or is there some free space left ? Also, did you made a factory reset after restoring emuNAND or did you choose to format USER in NxNandManager ? Is it only freezing for a particular title or every game ?
Thank you for feedback.

**Comment by Vampitech** [comment]
Hey @eliboa i tried with many sizes 7.0GB, 5.2GB and finally with 10GB (all FULL) in the first 2 cases i fit the partition with the exact size of the final size of the image generated with NXNandManager and chosen FORMAT the USER partition. in the final test i made a factory reset with a new generated resized image but this time i left the format option unticked. Same result in every test and size. The freezing are happening in menus and games alike.

Btw, emuMMC generated by Hekate (32gb) runs smooth in the same SDs that i made the tests. No freezes at all.  Maybe this fact can help. Thanks for your response.

**Comment by eliboa** [comment]
Thanks, i'll have to do some testing and try to reproduce the freezing. I'll get back to you.

**Comment by eliboa** [comment]
I forgot to ask. Are those freezing happening right after the first boot following the restore ? Or did you install anything before it happened ?

**Comment by Vampitech** [comment]
@eliboa The freezing occurs after the first boot. I tried with a factory clean NAND backup (USER partition was downsized to 5GB) same result. Now, the first time that i tried mini-emunand was in 3.0.0 version and worked flawless but in a new test i've downloaded that versión but when i flash the mini-emu keeps freezing. This time with a new Windows installed on my machine.

Btw, i've made test with a Python script on Linux that resize the USER partition too. For my suprise it worked. No freezing at all.

Maybe a windows related issue?  

(Image of my mini-emu generated with the Python script that i mentioned above) https://media.discordapp.net/attachments/599810571621236747/656914827540824124/image0.jpg?width=821&height=616

**Comment by Jatsotserah** [comment]
> @eliboa The freezing occurs after the first boot. I tried with a factory clean NAND backup (USER partition was downsized to 5GB) same result. Now, the first time that i tried mini-emunand was in 3.0.0 version and worked flawless but in a new test i've downloaded that versión but when i flash the mini-emu keeps freezing. I tried with another method using a Python script with same result. Wich leads me to think that is something related with my console :(

The same thing happens to me. No fix yet.

**Comment by CHAPU-Lin** [comment]
Tiene error hekate 5.1.3 a la hora de hacer eMMC RAW GPP se queda colgado en el segundo proceso.

**Comment by Gillou68310** [comment]
To add more info to this issue, this only happen to me when I wrote the resized image to a partition which size is less than 
31276924928 bytes (boot0+boot1+rawnand.bin)
