### ISSUE TITLE
error 26 when trying to access eMMC via rcm gui

### ISSUE THREAD

**Issue by Zombulu666** [eliboa/NxNandManager#16]
Everytime i try to access my switch via emmc option in rcmgui i got error in my switch screen,
saying : 

"error 26 trying to read command from host"

and it keep trying and trying and nothing happens

Can you help ? itry to backup my nand directly to my PC

**Comment by eliboa** [comment]
Not related to NxNandManager (may be related to TegraRcmGUI though).

Please use the official version of [memloader](https://github.com/rajkosto/memloader) which only requires files on SD (in addition with the payload file that still must be pushed through USB)
