### ISSUE TITLE
USER partition doesn't fully restore.

### ISSUE THREAD

**Issue by LiamMCW** [eliboa/NxNandManager#18]
When restoring an encrypted USER partition to a backup, it shows the progress, then suddenly skips to the end. I tested by restoring an all 0 file to the nand backup then dumping it again, and it stops at exactly 80000000 in a hex editor.
This is using the latest release on github.

**Comment by eliboa** [comment]
Did you try with another backup located on a different volume/drive ?
Also, did you resize USER partition ?
Are you restoring from a single partition file (user.bin) or from a complete dump (rawnand.bin or full nand.bin) ?

**Comment by LiamMCW** [comment]
I am restoring from a user.bin file filled with 00 to test, user partition is normal size, and I cant test with a different drive rn because I lack the disk space.

**Comment by kieranearth** [comment]
I having the same issue, When I restore from USER it will do the first 2gb fine and then skip straight the end and say restore complete. Is there a workaround to restore my USER? I’m going to try on my other computer now and I’ll try a few different locations, my user data is a straight dump from nxnandmanager and is 26GB

**Comment by tsl0922** [comment]
@kieranearth you can mount USER partition with HacDiskMount and copy/paste the actual files to backup/restore.

**Comment by kieranearth** [comment]
Thank you for your response but I'd solved the issue splitting the user
partition and merging it with a previous backup that was fine that working.
I hope this helps anyone else with this issue
