### ISSUE TITLE
Missing Source Files

### ISSUE THREAD

**Issue by rblakeslee** [eliboa/NxNandManager#19]
Seems to be some files missing.
These header files aren't in the source tree:  ui_opendrive.h

**Comment by eliboa** [comment]
These file are generated during compilation via qmake (QT Creator).

**Comment by rblakeslee** [comment]
Are there any other considerations if I'm trying to compile ins VS2019?   I basically have most of it working, but I don't see any method for converting to qmake in the QT tools in VS.
I'd like to try this via VS since that's the environment that I'm most familiar with.

**Comment by eliboa** [comment]
I'm not using VS anymore so I can't help you with this, sorry. What I can tell you is that Qt Creator is not that different from VS and is relatively easy to use. The whole GUI part of this project were done on Qt Creator so I think the easiest way to build the project is to install Qt

**Comment by rblakeslee** [comment]
Ok, I'll take that route. Thanks.
