### ISSUE TITLE
Cannot detect 2nd partition/EmuMMC raw partition

### ISSUE THREAD

**Issue by rblakeslee** [eliboa/NxNandManager#20]
I was wondering if you had plans to add support for raw EmuMMC partitions that are either A. the second partition on the drive and/or B. since raw part EmuMMC necessarily contains the BOOT1/BOOT2 partitions appended to the front  of the EFI data, the ability to detect and skip over the boot1/2 and just start reading/writing the raw partition at 8MB from the beginning of the FAT partition entry.

If these aren't on your radar, I was planning on branching this and trying to work my way through adding those abilities and once tested, perhaps merging back into the master. 
I did finally get my QT environment working so compiling was successful, but I'm unsure of what changes have been affected since the last 'release' and didn't want to duplicate any work.

**Comment by eliboa** [comment]
Hi, yes I do plan to let the user open any partition with NxNandManager. 
As of restoring FULL NAND (emunand) from RAWNAND, if that's what your talking about, it's a good idea and it shouldn't be difficult to implement it. But feel free to make a pull request if you want ;) (NxStorage::restore() is the where full restore is handled).
Glad to read that you managed to build the project ^^

**Comment by eliboa** [comment]
Hi, would you mind testing this [alpha version](https://drive.google.com/open?id=1HuqmJWiSTF0M4PkcTiALXCimBi9zUpBo) and telling me if you can open your 2nd emummc partition ?
Also, you should be able to restore emummc from a RAWNAND file. 
Btw, you can already dump rawnand from emuMMC => Options > Dump RAWNAND only

**Comment by rblakeslee** [comment]
Sure thing.  My current configuration is a 512GB sd with 2 partitions, fat32 for the boot stuff, then 400gb as raw with to which I restored a  working emuMMC to it. It does detect the partition and allow all the normal functionality, however for some reason when first starting the program and selecting open partition it takes a long time to scan for the partitions which causes a not-responding message.  This also occurs when alt-tabbing away from the window, it has to refresh the partition tables, even after it's been opened/decoded.
Given enough time it completes the scan and displays the available partitions.   It showed the fat32 partition in the selection mode.  

Perhaps changing it so it only scans removable storage and only raw partitions to speed it up.  There's no reason to scan a fat32 partition as a NAND.

What is the criteria that you're matching to find the partitions?  When its checking if it's a full nand or raw nand, I think it should be searching for the BOOT0 signature (000200000F0E00000000000000000000)  And then confirm that it's a raw partition by checking for the UEFI part signature (AA4546492050415254)  after skipping the first 8389118 bytes of the selected raw partition. Then you can resume doing whatever other partitioning checks you already have in place. 

To that end, it might be better to split the menu items into open RAW, or open FULL nands to speed up the detection, or maybe just adding a scanning progress bar instead.

I'll continue testing.
![Annotation 2020-02-23 224549](https://user-images.githubusercontent.com/16166898/75127647-4919e500-568e-11ea-92dc-ae8f02aca8fd.png)

**Comment by eliboa** [comment]
@rblakeslee, thank you so much for your feedback.
This new "Open drives" dialog scans all volumes/partitions, regardless of filesystem. It does not check wether a volume is a valid NAND (it previously worked that way, not anymore).  
I'm surprised it took so long to scan all volumes on your computer because the program now uses Windows API [native functions](https://github.com/eliboa/NxNandManager/blob/92d8d8600217b653b0de0fb024abc351c4dbd253/NxNandManager/res/win_ioctl.cpp#L101) to list volumes (i.e FindFirstVolume => FindNextVolume).
As "memloader" drives are sometimes mounted as offline drives, I also added [a loop](https://github.com/eliboa/NxNandManager/blob/92d8d8600217b653b0de0fb024abc351c4dbd253/NxNandManager/res/win_ioctl.cpp#L132) to detect theses offlines drives (which are not returned by the win32 api). Perhaps, this loop is to blame...
Scanning drives by looking for specific signatures would be slower I guess, so I prefer to let the user choose the volume he wants to open.  Only then the program will seek [magic numbers](https://github.com/eliboa/NxNandManager/blob/92d8d8600217b653b0de0fb024abc351c4dbd253/NxNandManager/NxStorage.cpp#L20) to identify the NAND type (RAWNAND, FULL NAND, etc). 

What I'm gonna do is to open a new thread (of execution) to scan all of the drives, in order to fix that "app not responding" issue, with a loading message in the meantime. 
Also, I remember that I created an emuMMC (via Hekate) on a FAT32 partition so I will check that after emuMMC creation, the partitions type turns to RAW, I'm not sure about that (it should though).

I'll get back to you for testing if you don't mind. Again, thank you :wink:

**Comment by eliboa** [comment]
new build for v4.0 alpha => https://drive.google.com/open?id=1HuqmJWiSTF0M4PkcTiALXCimBi9zUpBo

**Comment by rblakeslee** [comment]
Ok, did some more testing now that I got time to check out the latest build.   It looks like the issues with the slow scanning are gone.  Upon opening it, using the same SD card that I was tinkering with before all the exports and imports seem to work.

Just some suggestions on the UI:
I think one thing that needs either clarification or documentation is the unencrypted export.  When you export a partition with crypto set to None (i.e. System, since I have to roll back the system version on this particular card) If I choose passthrough zeroes, does this automatically decrypt the partition?  Or does it only leave the blocks of 0s as unencrypted and the rest is still encrypted?
If it decrypts it, it should force the crypto option to decrypt when passthrough is selected, and then grey out the crypto option, or vice versa, don't enable the passthrough option until decrypt is selected. 
The progress window stays up after a partition dump is complete.  IMO, it should probably close automatically or have a close button so it's more obvious that the process completed. 

When restoring from file, does the file need to be encrypted or will it re-encrypt automatically?  If the file is encrypted from an unaltered dump, would would it double encrypt the already encrypted file?

How does the format user partition option work if you're just dumping a single partition like System?
 I'll keep poking at it when I have more time.   I'm going to see if I can swing finding the source for Hacdiskmount because integrating the drive-mount option into this program would be phenomenal.

**Comment by rblakeslee** [comment]
I performed a straight dump that was verified from RAW nand, it was just the system partition, then opened up the SD card and tried to restore it and got a Not a Valid Nx store error.
I can't seem to restore any single partition to an identical SD card partition. 

Here's the debug log from the opening of the SD card up to the SYSTEM restore:

23:17:40.215 : NxHandle::initHandle() set for NxStorage, current pointer is 0000000000 - m_off_start = 0000000000, m_off_end = 63502AA1FF, crypto_mode = 0
23:17:40.220 : NxStorage::NxStorage() begins for \\?\Volume{be3fb9ef-54fe-11ea-9d85-380025a17e84}
23:17:40.220 : NxStorage::NxStorage() m_path is \\?\Volume{be3fb9ef-54fe-11ea-9d85-380025a17e84}
23:17:40.220 : NxHandle::initHandle() set for NxStorage, current pointer is 0000000000 - m_off_start = 0000000000, m_off_end = 73B2DCFBFF, crypto_mode = 0
23:17:40.221 : NxStorage::NxStorage() size is 496922065920 (diskFreeBytes = 0)
23:17:40.221 : NxStorage::NxStorage() - Looking for magic 43414C30 (CAL0) at offset 0000000000
23:17:40.221 : NxStorage::NxStorage() - Looking for magic 434552544946 (CERTIF) at offset 0000000680
23:17:40.221 : NxStorage::NxStorage() - Looking for magic 4546492050415254 (EFI PART) at offset 0000000200
23:17:40.221 : NxStorage::NxStorage() - Looking for magic 4546492050415254 (EFI PART) at offset 0000800200
23:17:40.221 : NxStorage::NxStorage() - MAGIC found at offset 0000800200, type is FULL NAND
23:17:40.221 : NxHandle::initHandle() set for NxStorage, current pointer is 0000000000 - m_off_start = 0000000000, m_off_end = 73B2DCFBFF, crypto_mode = 0
23:17:40.222 : NxHandle::initHandle() set for NxStorage, current pointer is 0000000000 - m_off_start = 0000000000, m_off_end = 73B2DCFBFF, crypto_mode = 0
23:17:40.222 : NxHandle::initHandle() set for NxStorage, current pointer is 0000000000 - m_off_start = 0000000000, m_off_end = 73B2DCFBFF, crypto_mode = 0
23:17:40.222 : NxPartition::NxPartition(parent, BOOT0, lba_start=0, lba_end=8191)
23:17:40.223 : NxPartition::NxPartition(parent, BOOT1, lba_start=8192, lba_end=16383)
23:17:40.223 : -- GPT header --
23:17:40.224 : starts at lba 1 (off 0x0000000200)
23:17:40.224 : backup header at lba 833082704 (off 0x634FAAA000)
23:17:40.224 : first use lba 34 (off 0x0000004400)
23:17:40.225 : last use lba 833082671 (off 0x634FAA5E00)
23:17:40.225 : GPT header CRC32 = 969997221
23:17:40.225 : Table CRC32 = 2068427514
23:17:40.226 : NxPartition::NxPartition(parent, PRODINFO, lba_start=16418, lba_end=24575)
23:17:40.226 : NxPartition::NxPartition(parent, PRODINFOF, lba_start=24576, lba_end=32767)
23:17:40.233 : NxPartition::NxPartition(parent, BCPKG2-1-Normal-Main, lba_start=32768, lba_end=49151)
23:17:40.233 : NxPartition::NxPartition(parent, BCPKG2-2-Normal-Sub, lba_start=49152, lba_end=65535)
23:17:40.234 : NxPartition::NxPartition(parent, BCPKG2-3-SafeMode-Main, lba_start=65536, lba_end=81919)
23:17:40.234 : NxPartition::NxPartition(parent, BCPKG2-4-SafeMode-Sub, lba_start=81920, lba_end=98303)
23:17:40.234 : NxPartition::NxPartition(parent, BCPKG2-5-Repair-Main, lba_start=98304, lba_end=114687)
23:17:40.234 : NxPartition::NxPartition(parent, BCPKG2-6-Repair-Sub, lba_start=114688, lba_end=131071)
23:17:40.234 : NxPartition::NxPartition(parent, SAFE, lba_start=131072, lba_end=262143)
23:17:40.234 : NxPartition::NxPartition(parent, SYSTEM, lba_start=262144, lba_end=5505023)
23:17:40.235 : NxPartition::NxPartition(parent, USER, lba_start=5505024, lba_end=833099055)
23:17:40.235 : Offset from hdr->alt_lba is 00634FAAA000
23:17:40.235 : NxHandle::initHandle() set for NxStorage, current pointer is 0000000000 - m_off_start = 0000000000, m_off_end = 63502AA1FF, crypto_mode = 0
23:17:40.235 : NxStorage::NxStorage() - backup GPT found at offset 63502AA000
23:17:40.236 : NxStorage::NxStorage() - TYPE IS FULL NAND
23:17:40.236 : NxHandle::initHandle() set for NxStorage, current pointer is 0000000000 - m_off_start = 0000000000, m_off_end = 63502AA1FF, crypto_mode = 0
23:17:40.239 : NxStorage::NxStorage() - firmware version = unknown
23:17:40.239 : NxStorage::setStorageInfo(FULL NAND)
23:17:40.239 : NxStorage::NxStorage() ends. Size is 426546733568 (diskFreeBytes = 0). type is FULL NAND - not splitted
23:17:40.239 : NxHandle::initHandle() set for PRODINFO, current pointer is 0000804400 - m_off_start = 0000804400, m_off_end = 0000BFFFFF, crypto_mode = 2
23:17:40.240 : NxHandle::initHandle() set for SYSTEM, current pointer is 0008000000 - m_off_start = 0008000000, m_off_end = 00A7FFFFFF, crypto_mode = 2
23:17:40.240 : NxHandle::initHandle() set for SYSTEM, current pointer is 0008000000 - m_off_start = 0008000000, m_off_end = 00A7FFFFFF, crypto_mode = 2
23:17:40.251 : NxHandle::initHandle() set for PRODINFOF, current pointer is 0000C00000 - m_off_start = 0000C00000, m_off_end = 0000FFFFFF, crypto_mode = 2
23:17:40.252 : NxHandle::initHandle() set for SAFE, current pointer is 0004000000 - m_off_start = 0004000000, m_off_end = 0007FFFFFF, crypto_mode = 2
23:17:40.254 : NxHandle::initHandle() set for USER, current pointer is 00A8000000 - m_off_start = 00A8000000, m_off_end = 63502A5FFF, crypto_mode = 2
23:17:40.254 : NxHandle::initHandle() set for USER, current pointer is 00A8000000 - m_off_start = 00A8000000, m_off_end = 63502A5FFF, crypto_mode = 2
23:17:44.071 : NxStorage::setKeys(keys.dat) - CRYPTO is GOOD
23:17:44.072 : NxStorage::setStorageInfo(FULL NAND)
23:17:44.072 : NxHandle::initHandle() set for PRODINFO, current pointer is 0000804400 - m_off_start = 0000804400, m_off_end = 0000BFFFFF, crypto_mode = 2
23:17:44.073 : NxHandle::initHandle() set for SYSTEM, current pointer is 0008000000 - m_off_start = 0008000000, m_off_end = 00A7FFFFFF, crypto_mode = 2
23:17:44.076 : Found NCA for fw 7.0.1
23:17:44.077 : NxHandle::initHandle() set for SYSTEM, current pointer is 0008000000 - m_off_start = 0008000000, m_off_end = 00A7FFFFFF, crypto_mode = 2
23:17:44.078 : NxStorage::setStorageInfo(FULL NAND) - Reading journal report (/save/80000000000000d1)
23:17:44.640 : NxHandle::initHandle() set for SYSTEM, current pointer is 0008000000 - m_off_start = 0008000000, m_off_end = 00A7FFFFFF, crypto_mode = 2
23:17:44.643 : NxStorage::setStorageInfo(FULL NAND) - Reading play report (/save/80000000000000a1)
23:17:52.404 : NxStorage::NxStorage() begins for G:/system 510.bin
23:17:52.404 : NxStorage::NxStorage() m_path is G:/system 510.bin
23:17:52.405 : NxHandle::initHandle() set for NxStorage, current pointer is 0000000000 - m_off_start = 0000000000, m_off_end = 009FFFFFFF, crypto_mode = 0
23:17:52.405 : NxStorage::NxStorage() size is 2684354560 (diskFreeBytes = 198364651520)
23:17:52.405 : NxStorage::NxStorage() - Looking for magic 43414C30 (CAL0) at offset 0000000000
23:17:52.405 : NxStorage::NxStorage() - Looking for magic 434552544946 (CERTIF) at offset 0000000680
23:17:52.406 : NxStorage::NxStorage() - Looking for magic 4546492050415254 (EFI PART) at offset 0000000200
23:17:52.406 : NxStorage::NxStorage() - Looking for magic 4546492050415254 (EFI PART) at offset 0000800200
23:17:52.406 : NxStorage::NxStorage() - Looking for magic 4546492050415254 (EFI PART) at offset 0001800200
23:17:52.406 : NxStorage::NxStorage() - Looking for magic 010021000E00000009000000 () at offset 0000000530
23:17:52.406 : NxStorage::NxStorage() - Looking for magic 504B3131 (PK11) at offset 00000013B4
23:17:52.407 : NxStorage::NxStorage() - Looking for magic 504B3131 (PK11) at offset 00000013F0
23:17:52.407 : NxStorage::NxStorage() - Looking for magic 504B3131 (PK11) at offset 0000001424
23:17:52.407 : NxStorage::NxStorage() - Looking for magic 504B3131 (PK11) at offset 00000012E8
23:17:52.407 : NxStorage::NxStorage() - Looking for magic 504B3131 (PK11) at offset 00000012D0
23:17:52.408 : NxStorage::NxStorage() - Looking for magic 504B3131 (PK11) at offset 00000012F0
23:17:52.408 : NxStorage::NxStorage() - Looking for magic 504B3131 (PK11) at offset 0000040AF8
23:17:52.408 : NxStorage::NxStorage() - Looking for magic 504B3131 (PK11) at offset 0000040ADC
23:17:52.408 : NxStorage::NxStorage() - Looking for magic 504B3131 (PK11) at offset 0000040ACC
23:17:52.409 : NxStorage::NxStorage() - Looking for magic 504B3131 (PK11) at offset 0000040AC0
23:17:52.409 : NxHandle::initHandle() set for NxStorage, current pointer is 0000000000 - m_off_start = 0000000000, m_off_end = 009FFFFFFF, crypto_mode = 0
23:17:52.410 : NxStorage::NxStorage() - TYPE IS UNKNOWN
23:17:52.410 : NxStorage::NxStorage() ends. Size is 2684354560 (diskFreeBytes = 198364651520). type is UNKNOWN - not splitted

**Comment by rblakeslee** [comment]
It seems the app isn't releasing previously opened files unless the app is fully closed in between operations. 
Did an export of the one system partition, then opened a disk, then opened a different image and the first file of the dumped system partition was still locked by the app.

I am able to restore the original dumped/encrypted partition back into a file or sd card, though.  

I'm guessing based on that behavior, currently we can only restore fully encrypted partitions and it won't accept unencrypted files for restore.  This would probably prevent you from restoring a partition exported from a different swich system into another image/sd because the encryption keys would be different and it wouldn't be able to identify the incoming file as a valid NX partition.

**Comment by eliboa** [comment]
Hi @rblakeslee and thank you for your response. 
Due to personnal reason, I was not able to work on this project lately and so to review all your feebacks. I released a beta version for [NxNandManager_v4.0](https://github.com/eliboa/NxNandManager/releases/tag/v4.0-beta) toay, a little bit in a rush.

About the "passthrough zeroes" option, it will decrypt clusters but will encrypt them back when copying, except for unallocated ones (filled with zeroes). In the end the output file/storage is  encrypted and can be restored, as such, to the Nintendo Switch.
I have not experienced your restore problem but i'll give it a look when i'll find some time.
