### ISSUE TITLE
emuMMC Backup GPT data lost after full dump

### ISSUE THREAD

**Issue by FusionFernia0000** [eliboa/NxNandManager#21]
After dumping emuMMC from SD card using the FULL DUMP option, "Backup GPT" in "Properties" shows NOT FOUND instead of an offset.

emuMMC partition accessed directly: 
![image](https://user-images.githubusercontent.com/20417687/75545955-8c939b00-5a62-11ea-9038-6b69c4b5633f.png)

File generated with FULL DUMP:
 ![image](https://user-images.githubusercontent.com/20417687/75545844-5229fe00-5a62-11ea-8cba-d4d1ec99bb69.png)

My very old MMC dump created by hekate (for reference):
![image](https://user-images.githubusercontent.com/20417687/75546142-e6946080-5a62-11ea-9a89-659b0f7d5546.png)

The missing of GPT table data results in HacDiskMount and ninfs unable to mount the MMC backups, therefore couldn't retrieve data resides in said backups.

![image](https://user-images.githubusercontent.com/20417687/75546450-8520c180-5a63-11ea-814a-db70c0a05b1c.png)
![image](https://user-images.githubusercontent.com/20417687/75546489-979afb00-5a63-11ea-9fd0-0db5e90d3132.png)

Tested using version v4.0a

**Comment by FusionFernia0000** [comment]
Also tried "Option > Dump RAWNAND only (FULL DUMP)", the generated RAWNAND.bin can now be read by HacDiskMount, backup GPT remains corrupted(?), and the dump cannot be read by NxNandManager (Input file is not a vaild NX storage).

![image](https://user-images.githubusercontent.com/20417687/75547940-03329780-5a67-11ea-8b2f-3d11e29488b3.png)

![image](https://user-images.githubusercontent.com/20417687/75548000-1a718500-5a67-11ea-92a6-1942b2b58a7c.png)

Tested with both my 8GB and 30GB emuMMC.

**Comment by eliboa** [comment]
Well done for finding this bug, you're helping me a lot 😉 
You can grab this [new build](https://drive.google.com/open?id=1HuqmJWiSTF0M4PkcTiALXCimBi9zUpBo) if you want to test yourself.
Thank you.

**Comment by FusionFernia0000** [comment]
RAWNAND dump can now be recognized by both HacDiskMount & ninfs & NxNandManager, primary and backup GPT are intact.

But if I use the full dump option HacDiskMount & ninfs still wouldn't recognize the generated dump (different error from above issues), NxNandManager reads it just fine.

![image](https://user-images.githubusercontent.com/20417687/75609329-7bba5680-5b42-11ea-90fd-8bc8e852fd45.png)

![image](https://user-images.githubusercontent.com/20417687/75609386-0438f700-5b43-11ea-859a-e7c69edd6121.png)

Also notice dumping speed is slightly faster now, nice bonus.

**Comment by FusionFernia0000** [comment]
My guess is that HacDiskMount or ninfs don't support having BOOT0 or BOOT1 at the front. If that's the case then maybe when doing a full dump you can store it into 3 files (BOOT0, BOOT1, rawnand.bin), just to make it more compatible. 

But if HacDiskMount or ninfs do support having BOOT0 or BOOT1 at the front then just leave this issue open.

**Comment by eliboa** [comment]
Yes, HackDiskMount simply can't detect full nand, only rawnand. It needs a file/volume that begins with a GPT. I guess it's the same for ninfs. 
You can already extract rawnand, boot0 and boot1 from full nand via NxNM though. Full dump will always dump the whole opened storage. 
Btw, you can also restore full nand from rawnand, or from boot0, boot1 or any partition. You'll have to do multiple partial restore in order to fully restore from rawnand, boot0 & boot1 files (3 in this case).

**Comment by eliboa** [comment]
Also feel free to give your opinion in [this thread](https://github.com/eliboa/NxNandManager/issues/17) if you think dumping full nand in 3 different files is a good thing.
