### ISSUE TITLE
Selection of the nand image file is not possible in the Emunand Creation Tool (v4.0 beta)

### ISSUE THREAD

**Issue by muxi1** [eliboa/NxNandManager#26]
Hello @eliboa, the selection of the nand image is not possible.

![2020-04-25 14_43_16-emuNAND creation Tool](https://user-images.githubusercontent.com/39792666/80280292-77a25380-8703-11ea-92bd-13c507558609.jpg)

**Comment by eliboa** [comment]
Hi @muxi1. Oops, you shouldn't be able to open emuNAND creation tool when no valid RAWNAND/FULL NAND storage is opened. I'll fix that.
Try to open RAWNAND before starting the tool and it should work fine.

**Comment by eliboa** [comment]
Fixed. Release updated.
