### ISSUE TITLE
"ERROR: Failed to get handle to output file/disk" after trying to create an emuNAND SD Partition.

### ISSUE THREAD

**Issue by leandrodeassis** [eliboa/NxNandManager#27]
![image](https://user-images.githubusercontent.com/889104/80645408-72b20c80-8a41-11ea-8fdb-1d8dbc287e26.png)

DEBUG: 
[error.txt](https://github.com/eliboa/NxNandManager/files/4554557/error.txt)

**Comment by eliboa** [comment]
Hi @leandrodeassis and thank you for reporting this.
Is your mmc an AES Security Card ? 
Or did you activate BitLocker on this drive ?

**Comment by deejay87** [comment]
Hi
Just to write i have the same error

**Comment by deejay87** [comment]
i'm going to test, cause strange when you create manually your emunand partition is on the right, here the program create to the left
i think after that we have to go on hekate and clic on "migrate" to create the folder "emummc" and emummc.ini

**Comment by leandrodeassis** [comment]
the emunand partition is on the left, only 4GB cause I resized to 4gb.

**Comment by deejay87** [comment]
Yes everything working for my first test :) 
have to test to resize now
Perfect program héhé

**Comment by leandrodeassis** [comment]
yep, working like a charm. amazing.
![2020043011521400-57B4628D2267231D57E0FC1078C0596D](https://user-images.githubusercontent.com/889104/80725452-78f3c780-8ad9-11ea-85f9-feb6cd999feb.jpg)

**Comment by eliboa** [comment]
damn, I forgot to add a manifest to force admin execution level at startup. At least it'll be easy to fix and there's nothing wrong with the code.
Glad it worked for you @leandrodeassis and thanks @deejay87 for your help

**Comment by eliboa** [comment]
Yep, fixed and v4.0-beta release updated. Thanks again folks.
