### ISSUE TITLE
Firmware version showing diffent values in Storage Information and Properties

### ISSUE THREAD

**Issue by leandrodeassis** [eliboa/NxNandManager#28]
![image](https://user-images.githubusercontent.com/889104/81478386-6ec97b80-91f3-11ea-8e92-3195353d2906.png)

**Comment by eliboa** [comment]
Strange bug, I'll look into it. My guess is that one version is derived from NCA, the other from pkg1 bootloader or from user journal.
Thank you for reporting this

**Comment by eliboa** [comment]
Downgraded firmware ? Was not able te reproduce. Please open new issue if it still happens on latest release.
