### ISSUE TITLE
"NxHandle::write - FAILED WriteFile - 87" when trying to FULL DUMP RAWNAND

### ISSUE THREAD

**Issue by leandrodeassis** [eliboa/NxNandManager#29]
this not happen when I dump partition separately, or i dump in other partition than C:\

![image](https://user-images.githubusercontent.com/889104/81533968-890f7080-933d-11ea-9c87-70f556cdaf7e.png)

**Comment by eliboa** [comment]
Hi @leandrodeassis, sorry I missed your issue.
Did you try with latest stable release ? 
Also, what is exact output path for your dump ?

**Comment by RickBruyninckx** [comment]
This problems still exists in version 5.2.
When i want to do a fulldump to E:/ it fails but to C:/ succeeds.
