### ISSUE TITLE
Input file/drive not a valid NX storage

### ISSUE THREAD

**Issue by annson24** [eliboa/NxNandManager#30]
Had this error on v4.0b, never on v3.0.3. My emummc was created using dd for windows from a nand backup created by hekate.

**Comment by annson24** [comment]
It's actually giving the error because the partition I was picking was the fat32 partition. I suspect v4.0b doesn't detect the emummc partition because I remove its drive letter. A thing that wasn't a problem on v3.0.3.

**Comment by eliboa** [comment]
If your emummc is an "hidden" partition, you should select the "drive" ("SD/MMC Generic" in the example below)
![image](https://user-images.githubusercontent.com/16166898/75127647-4919e500-568e-11ea-92dc-ae8f02aca8fd.png)
If your emuMMC is a "real" partition, then you should select a mounted volume (F: or G: in the example). BUT, if your partition is not a mounted volume, it should also work if you select the drive (the program will then perform a scan to retrieve the emuMMC volume, as it worked in previous releases).
Did you try that ?

**Comment by annson24** [comment]
I haven't tried that one yet, and I'm afraid I wouldn't be able to try it anymore as I already migrated to file-based emuMMC and emunand.
