### ISSUE TITLE
Support for hidden emuMMC images.

### ISSUE THREAD

**Issue by DarkMatterCore** [eliboa/NxNandManager#32]
emuMMC images can be stored in reserved SD card areas that are not asigned to any logical partitions referenced in the MBR/GPT, pretty much like 3DS emuNANDs used to work some years ago.

Making the emummc.ini file point to the start sector from a hidden emuMMC image makes it work perfectly fine with both fusee-primary.bin and Hekate + FSS0.

The only benefit from this setup would be avoiding the Windows format nag each time the SD card is inserted without resorting to custom OS fixes (like using a custom driver).

It would be a nice option for more experienced users. Parsing the emummc.ini file from the SD card or asking the user for the start sector number, and then jumping to the raw start sector would do the trick.

**Comment by DarkMatterCore** [comment]
This also offers the potential to fix compatibility with emuMMC images from deleted logical partitions, like the one from issue #30.

**Comment by eliboa** [comment]
Hello, 

It's a good idea but it would take more development and I'm not too involved in this project right now. I would suggest to mount emu raw GPP through Hekate/Nyx (in Tools > USB Tools) to be sure that the mounted drive can be opened with NxNandManager.

For now, the only supported "hidden emuNAND" (i.e. not described in MBR) has to start at sector 2 (as is the case for SX OS's hidden emuNAND, just after the MBR).
Except maybe for multiple "hidden" emuNAND on the same μSD, it should work most of the time.
It makes sense to locate the emunand raw data at this specific "unallocated" area, i.e right after MBR sectors and just before the first partition's start sector.

So if you have an hidden emuNAND starting at sector 2, you should be able to open it via "Open Drive" menu, then select a drive, not a partition ("SD/MMC Generic" in the example below)
![image](https://user-images.githubusercontent.com/16166898/75127647-4919e500-568e-11ea-92dc-ae8f02aca8fd.png)

If not, what is your emummc config ?
