### ISSUE TITLE
Why it must tick off format user partiton when resized nand in SX lite console

### ISSUE THREAD

**Issue by paulzheng136** [eliboa/NxNandManager#35]
i found a little strange thing to resize emunand in nxnandmanager 4.0.
i have a switch with sxcore and a switch lite with sxlite , both of them created files on microsd 's  emunand already.  when i want to resized the emunand as a minor image,  so i setup user partiton as 2gb,   i think it's a appropriate number. 
but if you choose to trim lite's emunand,  you have to tick off the "format user" option in frame,  if not,  nxnandmanager can't let it be trimed,  original size number with user partition will reset instantly in next step.
After that when  you trim the regular switch 's emunand,  it needn't  format user in nxnandmanager.   it means happened only with switch lite console.

Althought that's not a problem ,  well ,  i am only  curious about it.  oh maybe it's a kind of fortuity happening.

BTW,  2 consoles are all  updated 10.0.4

**Comment by eliboa** [comment]
Hi @paulzheng136. My guess is that your lite's emunand has more than 2GB of used space already. The program does not let you trim USER if you don't have enough free space in filesystem. The only way to trim an already "full" emunand is to tick off "Format User" checkbox. This is a protection to prevent unwanted data loss.

**Comment by paulzheng136** [comment]
yes,  i checked before create emunand as i want to make a clean emunand,  so i am sure it was initialized before.
thank you remind me that,  let me try once more.

**Comment by paulzheng136** [comment]
maybe i made a mistake before.  i perfer to choose format user when trimed emunand .
