### ISSUE TITLE
[Suggestion] Add the "close file/drive" action, and auto close if load another file/drive

### ISSUE THREAD

**Issue by CaiMiao** [eliboa/NxNandManager#36]
It is annoying that when you want to "safe remove" the drive but Windows just tell you drive is in use, as well I want to delete the unwanted nand backup I opened earlier in current instance (I manipulate NAND for research purpose so I have multiple copy to modify)

Let us have a close option and set them free for good.

**Comment by eliboa** [comment]
You are right, I should add that feature.
Added to my TODO list ;)

**Comment by CaiMiao** [comment]
Still no auto close when load another file, keep open
