### ISSUE TITLE
[Bug] Regarding partitial NAND backup incompatibility

### ISSUE THREAD

**Issue by CaiMiao** [eliboa/NxNandManager#37]
From Mariko on, BOOT0/1 partition is encrypted, should hide additional action when it's encrypted (and hide infos if you don't want to bother decrypt it).

Loading a partitial NAND backup informs me not a valid NX nand dump.
In my case it is a system partition dump from SXOS (filename `sys.bin`). It is like RAWNAND and have all partition from GPT table to `system` (from `user` on is absent), and HacDiskMount can load it with out problem.

**Comment by eliboa** [comment]
Indeed, NxNM doesn't support mariko's boot partitions yet.
I would be grateful if you could send me (eliboa@gmail.com) your mariko's BOOT0/1 so I can have some real binaries to use for tests. I would keep them private of course even though it's useless without the right keys.

Regarding your partial backup problem, I don't know what is causing the problem. I wasn't aware of that "system partition dump" in SX's bootloader. I'll look into it.

**Comment by CaiMiao** [comment]
I guess it may have to do with the absence of Backup GPT.

**Comment by CaiMiao** [comment]
I find another bug with the dump RAWNAND problem.
If you dump a RAWNAND from a trimmed FULLNAND, you will encounter a small issue that informs you checksum failure.
Also this step can produce you an RAWNAND incompatible with current version, while HacDiskMount can still load it without problem.

![QQ截图20200809041251](https://user-images.githubusercontent.com/4640483/89718076-538b2980-d9f7-11ea-99e5-61b3084c0262.png)
![QQ截图20200809041311](https://user-images.githubusercontent.com/4640483/89718088-5b4ace00-d9f7-11ea-919c-396aee9f7036.png)
![QQ截图20200809041432](https://user-images.githubusercontent.com/4640483/89718098-5e45be80-d9f7-11ea-8a59-cd8a4fa4f5ae.png)

**Comment by dezem** [comment]
Hi @eliboa any news on this to support Mariko Switch?

boot0 is also detected as boot1

**Comment by CaiMiao** [comment]
Can't load hekate style file-based Emunand as well.
not creating another issue as future implemention may involve with the problem.

**Comment by eliboa** [comment]
Support for mariko's BOOT0/1 has been added.
As for handling of resized dump it should work in next release.
Support for nand dump without  GPT backup: added to my todo list (#60)

**Comment by eliboa** [comment]
[v5.1](https://github.com/eliboa/NxNandManager/tree/v5.1) 👀
