### ISSUE TITLE
Move an Emunand (partition) from one switch to a different switch?

### ISSUE THREAD

**Issue by 38285760** [eliboa/NxNandManager#38]
Is it possible to move an Emunand (partition) from one switch to a different switch?
Both have the possibility of having emunand.
If so, how would the process be done?

I know it would be easier to create a new one and pass the saves with checkpoint and reinstall the games. But I want to keep the profile.

**Comment by CaiMiao** [comment]
backup (or resize directly) your current EmuNAND with the tool, use the backup to create on another SD card

**Comment by eliboa** [comment]
@CaiMiao gave the rights answers. I would recommand the second one if you can mount 2 mmc on your computer.

**Comment by 38285760** [comment]
> gave the rights answers. I would recommand the second one if you can mount 2 mmc on your computer.


> backup (or resize directly) your current EmuNAND with the tool, use the backup to create on another SD card
> 
> or plug both SD card to your PC, open the old one and directly create on the new one



First, shouldn't I make a change to keys taken from LockPick as they are different switches or are they compatible without doing anything?

**Comment by CaiMiao** [comment]
Ah I didn't notice that **different switch**... Then it won't work. At least all the saves would be validated with console specific keys. You have to begin from scratch.

**Comment by eliboa** [comment]
I did not payed attention enough :smile: 
Your emuNAND is console specific indeed.

**Comment by 38285760** [comment]
> did not payed attention enough 😄
> Your emuNAND is console specific indeed.

Is it impossible to change the internal keys of the emunand with the NxNandManager?

**Comment by CaiMiao** [comment]
> Is it impossible to change the internal keys of the emunand with the NxNandManager?
As I say the Horizon (Switch OS) will validate the saves (including system titles save), so it's meanless.

**Comment by eliboa** [comment]
> Is it impossible to change the internal keys of the emunand with the NxNandManager?

NxNandManager can only BIS decrypt (or encrypt) NAND partitions.  Basically, you get to see the files inside a partition - once decrypted - but some of theses files are stored encrypted with other console unique keys (such as titles saves). There are several layers of encryption, BIS is just the first and affects each cluster in the partition, regardless of the data type.

**Comment by 38285760** [comment]
Thanks for the reply! 

and is it possible to export a user profile from one emunand (switch 1) to another emunand (switch 2) or is it also impossible?

**Comment by CaiMiao** [comment]
don't know what you actually want, i guess you want to do a user transfer. you have two switch then just backup switch1 nand, transfer the specific user to switch2 with Horizon's local transfer feature, then restore switch1's nand

**Comment by 38285760** [comment]
> don't know what you actually want, i guess you want to do a user transfer. you have two switch then just backup switch1 nand, transfer the specific user to switch2 with Horizon's local transfer feature, then restore switch1's nand

My only goal is related to the game hours log that my profile has on Switch 1. I have an app called "NX Activity Log" that shows a complete log of hours of my profile on each game (number of hours, dates, etc).
I thought that copying the Emunand would be solved but you already told me that it cannot be done.

I understand that the file that has this information is somewhere in the Emunand. I would really like to get it as if it were a save that I retrieve from Checkpoint.
