### ISSUE TITLE
After hekate format the sd card emunand partition not accessible by NxNandManager on PC using sdcard reader

### ISSUE THREAD

**Issue by tomvita** [eliboa/NxNandManager#41]
I used NxNandManager to backup my SD emunand partition before using hekate to reformat the drive into FAT32. After the formating the SD card works fine on the switch but when I put the SD card into a sd card reader on PC NxNandManager can no longer see it.  I get "Input file/drive not a valid NX storage".

**Comment by eliboa** [comment]
Have you tried mounting your emunand through USB directly from Hekate (SD Tools) ?
