### ISSUE TITLE
Failed to write to output file/disk

### ISSUE THREAD

**Issue by Deadfalt999** [eliboa/NxNandManager#43]
Everytime I try to create a new emunand with my rawnand.bin I get this message. I don't get it.

**Comment by Deadfalt999** [comment]
To be more precise my sd card is formatted to the fat32 format and is completely empty.

**Comment by Deadfalt999** [comment]
And this error only appear when I try to create an emunand with the sd partition option.

**Comment by eliboa** [comment]
It looks like the program can't acces your SD card for writing raw disk sectors.
To gain access the program should unmount all mounted volumes on your mmc.

Please repeat the operation after starting the program in debug mode and send me the log please (use this release https://github.com/eliboa/NxNandManager/releases/tag/v4.0 to have access to debug console, NxNandManager_DEBUG.bat)
