### ISSUE TITLE
Doesnt work if using Onedrive synced.

### ISSUE THREAD

**Issue by cyblpt** [eliboa/NxNandManager#44]
This tool doesnt work if you are using OneDrive to sync with the desktop because it will not recognise it as a valid directory when trying to use any of the program functions, dump, restore, resize,etc none of that work with OneDrive i solved my own problem by just moving it to documents and work from there, not my directory of work this one lol :D but it works now at least, just letting you know so that you may fix it in the future, thanks for this great tool btw 👍 .

**Comment by eliboa** [comment]
Fixed. Next release coming soon.

**Comment by eliboa** [comment]
[v5.1](https://github.com/eliboa/NxNandManager/tree/v5.1) 👀
