### ISSUE TITLE
Incognito patching not working/Device ID not showing even after providing keyset

### ISSUE THREAD

**Issue by ssen-design** [eliboa/NxNandManager#46]
I have a Mariko Switch with SN starting with XKW5003. The Device ID of the switch is saying "Keyset needed" even though it has already been provided and whenever its PRODINFO has been modified, it gets stuck at the flash screen. Is it possible to and identify and rectify this issue?

**Comment by WoWant** [comment]
I have the same problem

**Comment by shensmart** [comment]
I have the same problem

**Comment by eliboa** [comment]
It would be useful if one of you could send me a copy of its PRODINFO + BISKEY (eliboa@gmail). I'll keep it private of course
I have no mariko unit so I can't test myself.

**Comment by plejboj** [comment]
Hello, I have this problem too on Mariko switch after keyset import (hidden partition). Tried directly by connecting SD card to PC and mounting via Hekate (read/write ON) - same result. I'll send you email with debug console output.

![image](https://user-images.githubusercontent.com/16122676/120891174-68305200-c607-11eb-9538-cebf0f87581e.png)

**Comment by eliboa** [comment]
[v5.1](https://github.com/eliboa/NxNandManager/tree/v5.1) 👀
