### ISSUE TITLE
SD Card not recognized

### ISSUE THREAD

**Issue by HellastoK** [eliboa/NxNandManager#48]
Hi ! 
I have a weird bug in my computer, my sd card is not recognized by my computer as a removable disk. So, when i want to create my emunand, i cant bc i dont have my sd card on "targeted disks". How can i fix that ?

**Comment by eliboa** [comment]
The drive has to be flagged as "removable" by Windows otherwise NxNM won't allow emunand creation. I'll might allow it for filebased emunand in the future
