### ISSUE TITLE
FULL DUMP emuMMC - Error 1016 

### ISSUE THREAD

**Issue by dezem** [eliboa/NxNandManager#5]
Hello @eliboa ,
i use Atmosphere emuMMC as partition.
If i dump my emuMMC partition.
I get following errorcode 1016, at the end of the dump process.

![emuMMC](https://user-images.githubusercontent.com/11005072/67638686-b50a5d80-f8e7-11e9-870d-4adc1aecb6a9.png)

My operating system is Windows 10 / 64bit.

**Comment by eliboa** [comment]
Hi @dezem, thank you for reporting this.
My guess is that copy went well but something went wrong just before or when hashing output file, right after dump is done. Did you see the blue progress bar ("Computing hash....) ? 
Maybe you're dump is good. Did you tried opening the bin file after dump ? 

Can you execute this command in window's console and give me the output please ? It would help me understand what's going wrong : 
```NxNandManager.exe -i \\.\PhysicalDrive3 -o fullnand.bin DEBUG_MODE ```
Thank you.

**Comment by dezem** [comment]
Hi @eliboa, thanks for the fast reply.
NXNandmanager don't creates the bin file at my selected path.

But I found the problem -> umlauts (äöü) at pathname.
Changed to another path working fine :-)

![emuMMC_2](https://user-images.githubusercontent.com/11005072/67702347-dd5e8e80-f9b1-11e9-9434-9580069ebbd2.png)

**Comment by eliboa** [comment]
Thank you for the feedback. Though it should work, "äöü" are valid UTF8 characters.
I'll look into it.

**Comment by eliboa** [comment]
Fixed, please download latest release : https://github.com/eliboa/NxNandManager/releases/tag/v3.0.1

**Comment by dezem** [comment]
Thanks for the fix! 👍 
Now it works with umlauts at the path
