### ISSUE TITLE
trying to dump a partition, checksum ALWAYS fails

### ISSUE THREAD

**Issue by NathanYumekoe** [eliboa/NxNandManager#51]
As stated in the title, checksum always fails. I'm not sure why. I'm using Hekate's UMS.

**Comment by Wat6656** [comment]
you have to mount if via memloader. using tegrarcm or the memloader payload.

**Comment by Filo97** [comment]
@Wat6656 memloader is incredibly slow compared to Hekate, so it's still a pretty major issue

**Comment by Wat6656** [comment]
@Filo97  just tested via Hekate, worked great for me. when do you get the error?

**Comment by Filo97** [comment]
After a partition finishes dumping and checking, it always tells me checksum failed

**Comment by eliboa** [comment]
Sorry for the late answer.
Is this still happening with latest release ? If so, please try the following steps : 

1. Open NxNandManager
2. In "Options" menu, select "Restart program in debug mode"
3. When program is restarted, select "Open drive" and open your NAND mounted via hekate
4. When you get the error, close the program and send me the file named "log_file.txt" created in the application's directory.
