### ISSUE TITLE
Add support for mounting partitions on Windows

### ISSUE THREAD

**Issue by Ryuuhou** [eliboa/NxNandManager#52]
This would be a really useful feature, being able to mount a partition as a physical drive in windows explorer to browse/modify content. One scenario would be mounting USER and being able to copy saves folder. This feature is in HacDiskMount (as this project pretty much replaces the abandoned HacDiskMount, it would be nice to also have that feature)

**Comment by eliboa** [comment]
Done. d7b5336869ee2398587d17846786ea7bb6e6b939
New release soon.
