### ISSUE TITLE
Need help restoring atmosphere backup

### ISSUE THREAD

**Issue by Superkidxl2099** [eliboa/NxNandManager#54]
I’ve heard that I would need nxnandManager to restore my old prodinfo since my switch’s serial number is xaw000, I was wondering if anyone would be willing to help me figure out how to restore it to the original xaw number with the older prodinfo (it has xaw(original serial number) on it, I just need assistance on how to restore it

My discord is Superkidxl2099#7685 please dm me here or on discord if you can assist me

**Comment by Masamune3210** [comment]
Depends on if the prodinfo dump is encrypted or not, regardless this is not a help center, this is for issues. Might have better luck on one of the popular switch discords or on gbatemp

**Comment by Wat6656** [comment]
all you need to do is restore the original prodinfo file, it is one of the options after you load your nand in the application and select prodinfo
