### ISSUE TITLE
Open local save Input file/drive not a valid NX storage

### ISSUE THREAD

**Issue by Dsseed** [eliboa/NxNandManager#57]
![1](https://user-images.githubusercontent.com/50006575/115102248-435f1d00-9f7c-11eb-97f7-047aab6d4bbf.jpg)
![2](https://user-images.githubusercontent.com/50006575/115102250-4528e080-9f7c-11eb-866a-081c4294cd37.jpg)
I just have the emuMMC made by Hekati, copy it to the PC, it can’t be opened

I tried Henkak's backup file rawand.bin, but it couldn’t be opened. I really don’t know what to do. Please help me.

**Comment by Aeuko** [comment]
It has been resolved. The path cannot have languages other than English, and there cannot be too many folders. It is recommended to open the root directory. I hope to help friends who encounter this problem.

**Comment by eliboa** [comment]
[v5.1](https://github.com/eliboa/NxNandManager/tree/v5.1) 👀
