### ISSUE TITLE
Atmosphére EmuNand Files

### ISSUE THREAD

**Issue by impeeza** [eliboa/NxNandManager#59]
Hi, I just try to use a folder of my Atmosphere file based EmuMMC files, but they are called:
- 00
- 01
- 02
- 03
- 04
- 05
- 06
- 07
no extension at all.

If I try to open the 00 file I get the error «Input file/drive is not a valid NX Storage», but if I rename the files to:
- rawnand.bin.00
- rawnand.bin.01
- rawnand.bin.02
- rawnand.bin.03
- rawnand.bin.04
- rawnand.bin.05
- rawnand.bin.06
- rawnand.bin.07
the set are loaded without problem.

Could be feasible to add the 00-07 name set to the correct filenames used by NxNandManager?

Thanks a lot for your great work.

**Comment by eliboa** [comment]
Hi @impeeza, I'll look into it. It

**Comment by impeeza** [comment]
Thanks a lot. Regards from Colombia

**Comment by eliboa** [comment]
@impeeza I wasn't able to reproduce this problem. It works fine for me :
![png](https://www.eliboa.com/switch/img/Capture20210531.png)

Can you try the following for me please : 

1. Open NxNandManager
2. In "Options" menu, select "Restart program in debug mode"
3. When program is restarted, select "Open file" in "File" menu and open the file named "00".
4. When you get the error, close the program and send me the file named "log_file.txt" created in the application's directory.

Thank you in advance.

**Comment by impeeza** [comment]
Hi, following your instructions, I did take several test, and find what the problem is related to the path having "." on it.

At first I did think was the spaces on the path, because the files are on the folder:
`h:\Emuladores\Nintendo Switch\Respaldos\2021_05_05 - Atmosphère 19.1 firmware 12.0.1\emummc\HPE0\eMMC\`

![image](https://user-images.githubusercontent.com/41979604/120231492-21151c00-c217-11eb-9898-eb739a2a8fa7.png)


so I renamed the folders on path to:
`h:\Emuladores\NintendoSwitch\Respaldos\2021_05_05-Atmosphere19.1firmware12.0.1\emummc\HPE0\eMMC\`

and no luck, doesn't work neither.


Then I move the files to:
`c:\ATM\HPE0\eMMC\00`
And the files are opened well, 
![image](https://user-images.githubusercontent.com/41979604/120231768-bf08e680-c217-11eb-9e87-1ad1f24ba968.png)



So I did think about the length of the folder and put the files on folder:
`c:\ATM\Carpeta1\Carpeta2\Carpeta3\Carpeta4\Carpeta5\Carpeta6\Carpeta7\Carpeta8\Carpeta9\HPE0\eMMC\`
And still open with out problem, 

Then renamed a parent folder to put several "." on it:
`c:\ATM\Carpeta1\Carpeta2\Carpeta3\Carpeta4\Carpeta5\Carpeta6\Carpeta7\Carpe\Ca.rp.et.a9\HPE0\eMMC\`
and then the files do not open.

[log_file_antes renombrar.txt](https://github.com/eliboa/NxNandManager/files/6571852/log_file_antes.renombrar.txt) is the log file when the process fail,

[log_file_Despues renombrar.txt](https://github.com/eliboa/NxNandManager/files/6571854/log_file_Despues.renombrar.txt)
[log_file_enC.txt](https://github.com/eliboa/NxNandManager/files/6571855/log_file_enC.txt)  re the files when process works fine.


Thanks a lo for your great work

**Comment by eliboa** [comment]
Thank you impeeza, it helps a lot. I think you're right, looks like it's related to path containing dots.
I'll let you know when the bug is fixed
