### ISSUE TITLE
Emummc Full Restore Error

### ISSUE THREAD

**Issue by pipezierra** [eliboa/NxNandManager#6]
FW 9.0.1
Emummc sd partition.
it can read but it can make a full or partial restore directly to EMUMMC.
i am triying to add the incognito feuture to my EMUMMC but i cant upload it

**Comment by eliboa** [comment]
Hi and thank you for reporting this. Can you give more details please, like the error you get or a screenshot? Incognito applies to open drive/file, no need to make a full restore.

**Comment by pipezierra** [comment]
![Sin título](https://user-images.githubusercontent.com/20825272/67660748-81522680-f92d-11e9-926d-1183c640e676.jpg)

sure

**Comment by pipezierra** [comment]
also i tried different micro sd adapters and different micro sd cards

**Comment by eliboa** [comment]
@pipezierra, I was able to reproduce this bug. I'll look into it and let you know when this is fixed.

**Comment by eliboa** [comment]
Fixed : bd4914813f75eb7b7545661da5f23b9170042495
new release will be available soon

**Comment by pipezierra** [comment]
> Fixed : [bd49148](https://github.com/eliboa/NxNandManager/commit/bd4914813f75eb7b7545661da5f23b9170042495) [704dc26](https://github.com/eliboa/NxNandManager/commit/704dc268d8b6075b42512d09c8d3357f158a0246)
> new release will be available soon

WOW, Thanks for your fast reply 👍

**Comment by eliboa** [comment]
https://github.com/eliboa/NxNandManager/releases/tag/v3.0.1
