### ISSUE TITLE
Formatting USER partition using the NXNanamanager does not remove everything but instead it generates corrupted files.

### ISSUE THREAD

**Issue by sthetix** [eliboa/NxNandManager#61]
Hello, as the title says, when we format the user partition using the app, it generates some corrupted files and folders like this one :

![image](https://user-images.githubusercontent.com/22261135/122134916-bb0cd380-ce69-11eb-9d5f-2f754cf92dda.png)

but we won't find that issue if we mount the partition using hacdiskmount and format it manually.

can you fix that problem?

Thanks! you are great!

**Comment by eliboa** [comment]
Oh, there's obvioulsy a problem somewhere :open_mouth: 
Because of holidays, I don't know when.. but I'll look into it.
Thank you sthetix :+1:

**Comment by sthetix** [comment]
You are welcome, enjoy your holiday.

**Comment by eliboa** [comment]
[v5.1](https://github.com/eliboa/NxNandManager/tree/v5.1) 👀

**Comment by sthetix** [comment]
Thank you for the latest release. You are awesome!
