### ISSUE TITLE
Firmware 13.1.0

### ISSUE THREAD

**Issue by impeeza** [eliboa/NxNandManager#69]
Hi, there is any needed to support firmware 13.1.0 dumps? mine shows:
![image](https://user-images.githubusercontent.com/41979604/142782986-05bf751a-c604-4aa4-8202-c40951b4d35d.png)

a set of dumps from the same Switch before update shows the correct firmware version:
![image](https://user-images.githubusercontent.com/41979604/142783062-5ee6f87c-5b95-44cf-8b57-cc94cf79fd6c.png)

booth captures are using the same KeySet.

**Comment by eliboa** [comment]
138b3d69d65b05bccc8f40ec801e122fb0e57615
c49adebc3ea8ea1e35f92534d8c7892fe6a07701

**Comment by eliboa** [comment]
[v5.1](https://github.com/eliboa/NxNandManager/tree/v5.1) 👀
