### ISSUE TITLE
3.0.1 couldn't open emuMMC partition with Windows 7

### ISSUE THREAD

**Issue by dezem** [eliboa/NxNandManager#7]
Hi @eliboa,
if found a new bug in the 3.0.1

With version 3.0.1 it's not possible to open a emuMMC partition with Windows 7.
If you use version 3.0.0 its working.

![NxNandManager v3 0 0 by eliboa](https://user-images.githubusercontent.com/11005072/68068798-79ddb380-fd59-11e9-83cf-6871d05931e2.png)
![NxNandManager v3 0 1 by eliboa](https://user-images.githubusercontent.com/11005072/68068799-79ddb380-fd59-11e9-827e-5a075b16fb8c.png)

**Comment by eliboa** [comment]
Thank you again dezem. Had to found a computer running on Win7 to reproduce this bug.
I updated 3.0.1 release with a small fix, can you [redownload it](https://github.com/eliboa/NxNandManager/releases/download/v3.0.1/NxNandManager_v3.0.1_x64.zip) and tell me if it works for you please ?

**Comment by dezem** [comment]
Perfectly :+1: 
Yes it works now big thanks for the fast fix :-)

![New_Version_NxNandManager v3 0 1 by eliboa](https://user-images.githubusercontent.com/11005072/68070450-c1226f00-fd6e-11e9-843e-193a3f4c4adb.png)
![New_Version_NxNandManager_v3 0 1_x64_2](https://user-images.githubusercontent.com/11005072/68070451-c1226f00-fd6e-11e9-8a85-5f26ee6287b7.png)
