### ISSUE TITLE
Checksum Mismatch Occurs when Dumping RAWNAND from FULLNAND.

### ISSUE THREAD

**Issue by HeyItsJono** [eliboa/NxNandManager#71]
It seems that if I try to use the Options --> Dump RAWNAND Only (FULL NAND) feature, NxNandManager generates an MD5 for the FULLNAND and compares that to the MD5 of the generated RAWNAND, which obviously will always be different and throw an error. Is there any way to confirm the integrity of the generated RAWNAND dump?

**Comment by HeyItsJono** [comment]
Also interestingly, the RAWNAND Only bin file's hash differs if you dump RAWNAND directly from the open drive vs. first dumping FULL NAND then opening it in NxNandManager and extracting RAWNAND from the FULL NAND dump. Is there any reason for this?

**Comment by eliboa** [comment]
[v5.1](https://github.com/eliboa/NxNandManager/tree/v5.1) 👀

**Comment by HeyItsJono** [comment]
Thank you!
