### ISSUE TITLE
Incognito hanging on mariko devices

### ISSUE THREAD

**Issue by Ryuuhou** [eliboa/NxNandManager#79]
Mariko console hangs on Switch logo after applying incognito until prodinfo is restored.

This is the same issue exosphere blanking had in the beginning since it copied blawar's incognito. I assume yours is also a copy of blawar's incognito which blanks an important key required for newer marikos to boot.

https://github.com/Atmosphere-NX/Atmosphere/commit/f051f707ed99b6fd4a4249309d92064801b1e468 
^ the above documents the key that cannot be blanked

**Comment by OrGoN3** [comment]
Exosphere prodinfo blanking has nothing to do with blawars. They work VERY differently.

Not being able to apply incognito aside from possibly exosphere on Mariko systems is well known in the scene, and any decent guide will warn you about this.

**Comment by eliboa** [comment]
TODO: Remove incognito feature as is now obsolete and dangerous. 
Instead, user should apply cal0's blanking via Exosphère.

**Comment by Ryuuhou** [comment]
> Exosphere prodinfo blanking has nothing to do with blawars. They work VERY differently.
> 
> Not being able to apply incognito aside from possibly exosphere on Mariko systems is well known in the scene, and any decent guide will warn you about this.

actually exosphere blank was based off incognito and worked identically until it was changed for mariko devices

> TODO: Remove incognito feature as it's now obsolete and dangerous. Instead, user should apply cal0's blanking via Exosphère.

I would prefer something more permanent, could you think about modifying it to match exosphere?

**Comment by Masamune3210** [comment]
Exosphere does it on the fly, so it may not be possible to do it to the raw image in the same way, not sure though

**Comment by eliboa** [comment]
I don't have a mariko unit. Can someone test this build please ?
https://drive.google.com/file/d/1ec3yc3wToemKppm0Ltu2fg-8hxeOyuvW/view?usp=sharing

**Comment by Ryuuhou** [comment]
Tested and it works! Thank you for deciding to support mariko
