### ISSUE TITLE
Partition not found in "input"

### ISSUE THREAD

**Issue by medber** [eliboa/NxNandManager#8]
When trying to write back a 8.1 backup after upgrading to 9.01 via ChoiDujourNX (which kinda bricked my switch somehow) I get a **Partition not found in "input"** error after flashing back the BCPKG2-1-6 backups. All other single backups work flawless though.

Now when I start homebrew in the old backup (without reflashing these bckpg2 packages) I get Error 2162-0002 when starting any app. Trying to start "recovery mode" of the switch gives me bluescreen. *help* ;=)

Is this a bug or am I too stupid to understand the "error" ;) ? ;)
Win10 1903 x64 on NxNandManager v3.0.1

![error](https://user-images.githubusercontent.com/6376844/68077255-e50ea080-fdc0-11e9-96ea-d1aa45eebb56.PNG)

**Comment by medber** [comment]
Restoring with v2.0.2 works flawless. Just rescued my switch with it! ;)
Ninty Restore mode works again...

**Comment by eliboa** [comment]
Hi @medber and thank you for reporting this. Don't worry this is a bug, you're not stupid ^^.
Can you do a test with this build and tell me if it works ? => https://drive.google.com/open?id=1b5MPy7PCckCn9aIGwdOtVjvwgx-uISto
Thank you

**Comment by medber** [comment]
> 
> 
> Hi @medber and thank you for reporting this. Don't worry this is a bug, you're not stupid ^^.
> Can you do a test with this build and tell me if it works ? => https://drive.google.com/open?id=1b5MPy7PCckCn9aIGwdOtVjvwgx-uISto
> Thank you

Works flawless now. Version Number is @ 3.01 in titlescreen ;)
Haven´t tried Fullbackup RAWNAND.BIN though. Takes too long...

THANK YOU for such a quick reaction...

**Comment by eliboa** [comment]
https://github.com/eliboa/NxNandManager/releases/tag/v3.0.2
