### ISSUE TITLE
PKG1/2 Corruption

### ISSUE THREAD

**Issue by mistervampi** [eliboa/NxNandManager#80]
Hi! Recently i created an emunand from NXNandManager and i tried to update to 14.0.0 from 13.2.1 with Daybreak, Daybreak throws me an error 0x00234c02 and it won't let me update from there. Then I created an emunand from my Sysnand which was on 14.0.0 and when trying to start the emunand, Hekate throws me an error telling me that it couldn't decrypt PKG1/2. When performing the emunand directly with Hekate, everything goes normally. Even Daybreak allows for seamless updates. I am assuming there is something inside NXNandManager that corrupts the PKG1/2. It would be good if you take a look at it. Thank you for your attention and I hope you continue with your wonderful work.

**Comment by eliboa** [comment]
Hi @mistervampi. I'll look into it. Is the problem occurring on a file based or partition based emunand ? Emuanand has been resized ?

**Comment by mistervampi** [comment]
Hi @eliboa 

Occurs on:
- File Based emunand
- Resized to 10GB

Haven't tested with RAW partitioned emunand.  I will give it a try with another SD and see if the same problem occurs.

**Comment by eliboa** [comment]
Using latest version of NxNandManager, Hekate, AMS & Daybreak, I wasn't able te reproduce the error.
- Created a 5GB file based emunand from 8.1 SYSNAND using NxNM. Updated to 13.2.1 OK. Then updated to 14.0 => OK.
- Created a 32GB file based emunand from 8.1 SYSNAND using NxNM. Then updated to 14.0 => OK.
😞

**Comment by mistervampi** [comment]
So weird. I'll try again with another SD and lower firmwares.

**Comment by Masamune3210** [comment]
Could have been a slightly corrupted file causing issues with the update process

**Comment by mistervampi** [comment]
Hi again

I tried with this scenario:
- Hooked Hakate with NxNM and made a full RAWNAND Dump to PC.
- Then, created a 10GB file based Emunand from 14.0 SYSNAND RAWDUMP.
- Boot OK (In previous test gave me Blackscreen with fuusee.bin - PKG1/2 missmatch message with hekate)
- Downgraded With Daybreak to 13.2.1, OK (In previuos tests Daybreak gave me 0x00234c02 NCA Corrupted)
- Updgraded With Daybreak to 14.0, OK


I swear the days before when I faced that error message with Daybreak, I tried many scenarios looking for a solution. I guess there was a problem with a previous RAWNAND dump that maybe it was corrupted for any strange reason. 

Now i can be sure 100% it was not a problem with NxNM. 
Sorry if this may have caused confusion.

You can close this issue
