### ISSUE TITLE
Cannot run chkdsk on mounted partitions

### ISSUE THREAD

**Issue by stanleyws** [eliboa/NxNandManager#83]
I'm trying to run check disk for my emunand partition as it's created with old version of hekate on my oled switch, and only half of its original size is available. According to hekate's latest release, this issue can be fixed with check and repair partition. I mounted the user partition without any issue, but running error checking tool in drive properties does nothing, and running chkdsk on command prompt gives following error:
```
The type of the file system is RAW.
CHKDSK is not available for RAW drives.
```
Is it possible to check file system and remove damaged files with nxnandmanager?

**Comment by eliboa** [comment]
A RAW partition comes without any filesystem. The purpose of CHKDSK is to scan filesystem.

NxNandMananger can mount partitions inside your partition based emunand but only as "virtual" filesystem so CHKDSK won't work either.

**Comment by stanleyws** [comment]
Thanks for the reply. So I guess the check filesystem feature is not available in nxnandmanager due to how mounting is implemented? If so I'll close the issue and try another tool.

**Comment by eliboa** [comment]
Exactly. CHKDSK might work with NAND partitions mounted via **HacDiskMount**, you should give it a try.
