### ISSUE TITLE
The Mount Button is not clickable

### ISSUE THREAD

**Issue by KamiSquadX** [eliboa/NxNandManager#85]
I just downloaded the program, opened it, clicked open drive, selected the Card Reader, clicked the System partition, and is unable to click the Mount button because it's greyed out.

Why is that?

**Comment by eliboa** [comment]
You have to import your BIS keys first (Options > Configure keyser or CTRL+K) .

**Comment by KamiSquadX** [comment]
My BIS Keys? I just used Lockpick_RCM to generate the keys. Now what? why isn't this part of the instructions on how to use NXNandManager?

**Comment by KamiSquadX** [comment]
My BIS Keys? Ok. I just used Lockpick_RCM to generate the keys. It can mount now.

**Comment by KamiSquadX** [comment]
Thanks
